openapi: 3.0.0
info:
  title: API do Agente de Catalogação de IA para Património Cultural
  version: v1.0.0
  description: |
    Esta API permite interagir com o Agente de Catalogação de IA para realizar tarefas como:
    - Catalogar novos itens culturais.
    - Buscar referências e informações sobre itens existentes.
    - Gerir configurações da ontologia (conceptual).
    - Interagir com o agente através de um chatbot (via esta API).

servers:
  - url: http://localhost:5000/api/v1 # URL de exemplo, a ser definido na implementação real
    description: Servidor de desenvolvimento local

paths:
  /catalog:
    post:
      summary: Submete um novo item para catalogação
      description: Recebe os dados de um item cultural e o processa para catalogação, incluindo a ligação de referências e a geração de RDF.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item_data:
                  type: object
                  description: Dados principais do item a ser catalogado (ex: título, autor, descrição, identificadores).
                  example:
                    title: "Vaso Ming Antigo"
                    author: "Dinastia Ming"
                    description: "Um vaso de porcelana azul e branca do século XV."
                    keywords: ["vaso", "ming", "porcelana"]
                source_info:
                  type: object
                  description: (Opcional) Informações sobre a fonte dos dados do item.
                  example:
                    uri: "http://museu.example.com/api/items/123"
                    type: "api_json_source"
      responses:
        '201':
          description: Item catalogado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "sucesso"
                  message:
                    type: string
                    example: "Item catalogado e URI RDF gerada."
                  item_uri_rdf:
                    type: string
                    format: uri
                    example: "http://example.org/patrimonio/Vaso_Ming_Antigo"
                  linked_uris:
                    type: array
                    items:
                      type: string
                      format: uri
                    example: ["http://example.org/autor/Dinastia_Ming", "http://dbpedia.org/resource/Ming_dynasty"]
        '400':
          description: Pedido inválido (ex: dados em falta).
        '500':
          description: Erro interno do servidor.

  /search:
    get:
      summary: Realiza uma busca no acervo catalogado e em fontes externas
      description: Permite buscar itens culturais com base em palavras-chave, consultando o repositório RDF e, opcionalmente, fontes externas.
      parameters:
        - name: query
          in: query
          required: true
          description: Termo ou frase de busca.
          schema:
            type: string
            example: "artefactos egípcios"
        - name: sources
          in: query
          required: false
          description: Fontes a serem consultadas (separadas por vírgula, ex: "local,web,europeana"). Default é "local".
          schema:
            type: string
            example: "local,web"
        - name: validate_reliability
          in: query
          required: false
          description: Se deve tentar validar a confiabilidade das fontes externas.
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Resultados da busca.
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  results:
                    type: array
                    items:
                      type: object # Estrutura do resultado a ser definida
                      properties:
                        uri:
                          type: string
                          format: uri
                        title:
                          type: string
                        snippet:
                          type: string
                        source:
                          type: string
        '400':
          description: Parâmetros de busca inválidos.

  /config/ontology:
    get:
      summary: Obtém a configuração da ontologia ativa
      description: Retorna os detalhes da configuração da ontologia que está a ser utilizada pelo agente.
      responses:
        '200':
          description: Configuração da ontologia ativa.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OntologyConfig'
    put:
      summary: Atualiza a configuração da ontologia ativa (conceptual)
      description: Permite ao utilizador especificar um novo ficheiro de configuração de ontologia ou modificar parâmetros. (Implementação futura)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OntologyConfigUpdate'
      responses:
        '200':
          description: Configuração da ontologia atualizada com sucesso.
        '400':
          description: Dados de configuração inválidos.

components:
  schemas:
    OntologyConfig:
      type: object
      properties:
        ONTOLOGY_FILE_PATH:
          type: string
          format: path
        RDF_BASE_URI:
          type: string
          format: uri
        ITEM_CLASS:
          type: string
        TITLE_PROPERTY:
          type: string
        AUTHOR_PROPERTY:
          type: string
        DESCRIPTION_PROPERTY:
          type: string
        PREFIXES:
          type: object
          additionalProperties:
            type: string
            format: uri
      example:
        ONTOLOGY_FILE_PATH: "/home/ubuntu/agente_catalogador_ia/ontologies/exemplo_ontologia.ttl"
        RDF_BASE_URI: "http://example.org/patrimonio/"
        ITEM_CLASS: "pc:ObraCultural"
        TITLE_PROPERTY: "pc:temTitulo"
        AUTHOR_PROPERTY: "pc:temAutor"
        DESCRIPTION_PROPERTY: "dcterms:description"
        PREFIXES:
          pc: "http://example.org/patrimonio/ontology#"
          rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"

    OntologyConfigUpdate:
      type: object
      properties:
        active_ontology_config_file:
          type: string
          description: Nome do ficheiro JSON de configuração da ontologia (localizado em /ontologies).
          example: "minha_ontologia_customizada.json"
        # Outros parâmetros poderiam ser adicionados para modificação direta

